cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: abc
    laure:
      email: laure.margot@bluewin.ch
      name: Laure
      password: $2b$12$.cVDaelXpD3bG3lCyWY/XeUNoFq/FW1ibcsJ8DpJ0vT3brRwcsmHW
    leoniensb:
      email: leoniensb@email
      name: Leonie
      password: $2b$12$drdaBy5vj.8vIGFBYIkOkewcn0csRywq387rlDjlG5Mm0wXDlr.me
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: def
preauthorized:
  emails:
  - melsby@gmail.com
