cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: abc
    laure:
      email: laure.margot@bluewin.ch
      name: Laure
      password: $2b$12$.cVDaelXpD3bG3lCyWY/XeUNoFq/FW1ibcsJ8DpJ0vT3brRwcsmHW
    leo:
      email: leonie.nussbaum@unil.ch
      name: Leonie2
      password: $2b$12$fMhQDkvusXNpzRTfT7PqX.oRv4Abyt6GHftDDBcbNG9znI5EkE4S6
    leonie:
      email: leoniensb@email.com
      name: Leonie
      password: $2b$12$FtNZK0WGGGvSsr7GRP69Luk6RO/VZpYoX1KzfR1g6Nhb1qkVircly
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: def
preauthorized:
  emails:
  - melsby@gmail.com
